name = "Advent"
version = "0.1.0"
defaultTargets = ["advent"]
srcDir = "src"

[[lean_lib]]
name = "Advent"

[[lean_lib]]
name = "Utils"


[[lean_exe]]
name = "day01"
root = "Advent.Day01"

[[lean_exe]]
name = "day02"
root = "Advent.Day02"

[[lean_exe]]
name = "day03"
root = "Advent.Day03"

[[lean_exe]]
name = "day04"
root = "Advent.Day04"

[[lean_exe]]
name = "day05"
root = "Advent.Day05"

[[lean_exe]]
name = "day06"
root = "Advent.Day06"

[[lean_exe]]
name = "day07"
root = "Advent.Day07"

[[lean_exe]]
name = "day08"
root = "Advent.Day08"

[[lean_exe]]
name = "day09"
root = "Advent.Day09"

[[lean_exe]]
name = "day10"
root = "Advent.Day10"

[[lean_exe]]
name = "day11"
root = "Advent.Day11"

[[lean_exe]]
name = "day12"
root = "Advent.Day12"

[[lean_exe]]
name = "day13"
root = "Advent.Day13"